import type {
  AnalysisJob,
  AnalysisResult,
  AuditLog,
  Device,
  Finding,
  FrameworkDefinition,
  ReportItem,
  RemediationTask,
  TrainingItem,
  UploadRecord,
} from '../types'

export const vendorOptions = ['Cisco', 'Palo Alto', 'Fortinet', 'Juniper', 'Arista', 'HPE Aruba', 'SonicWall']

export const frameworkOptions = ['CIS Benchmarks', 'NIST SP 800-53', 'DISA STIG', 'ISO/IEC 27001']

export const devices: Device[] = [
  {
    id: 'dev-001',
    name: 'Core-Edge-01',
    vendor: 'Cisco',
    model: 'ASR 1002-X',
    serialNumber: 'CSR-8923A1F',
    firmware: '17.09.05a',
    ipAddress: '10.10.10.11',
    deviceType: 'Router',
    complianceScore: 92,
    risk: 'Low',
    lastScan: '2026-08-25T08:14:00Z',
    status: 'Compliant',
    location: 'Primary DC',
  },
  {
    id: 'dev-002',
    name: 'FW-Perimeter-A',
    vendor: 'Palo Alto',
    model: 'PA-5400',
    firmware: '11.0.4-h5',
    serialNumber: 'PAN-7712B1',
    ipAddress: '10.10.20.4',
    deviceType: 'Firewall',
    complianceScore: 78,
    risk: 'Moderate',
    lastScan: '2026-08-25T07:54:00Z',
    status: 'Warning',
    location: 'Internet Edge',
  },
  {
    id: 'dev-003',
    name: 'FortiGate-Edge',
    vendor: 'Fortinet',
    model: 'FG-200F',
    serialNumber: 'FGT-5521',
    firmware: '7.2.5',
    ipAddress: '10.10.30.12',
    deviceType: 'Firewall',
    complianceScore: 66,
    risk: 'High',
    lastScan: '2026-08-25T06:22:00Z',
    status: 'Non-Compliant',
    location: 'Branch Office',
  },
  {
    id: 'dev-004',
    name: 'Leaf-01',
    vendor: 'Arista',
    model: '7050X3',
    serialNumber: 'ARR-2281',
    firmware: '4.31.3F',
    ipAddress: '10.20.10.8',
    deviceType: 'Switch',
    complianceScore: 88,
    risk: 'Low',
    lastScan: '2026-08-25T08:43:00Z',
    status: 'Compliant',
    location: 'Leaf Rack A',
  },
  {
    id: 'dev-005',
    name: 'MX-Transit',
    vendor: 'Juniper',
    model: 'MX204',
    serialNumber: 'JNP-9314',
    firmware: '21.4R3-S2.3',
    ipAddress: '10.30.40.2',
    deviceType: 'Router',
    complianceScore: 57,
    risk: 'Critical',
    lastScan: '2026-08-24T22:05:00Z',
    status: 'Non-Compliant',
    location: 'Transit Core',
  },
  {
    id: 'dev-006',
    name: 'Aruba-Access',
    vendor: 'HPE Aruba',
    model: 'CX 6200',
    serialNumber: 'ARU-9011',
    firmware: '10.12.1000',
    ipAddress: '10.40.20.15',
    deviceType: 'Access Switch',
    complianceScore: 83,
    risk: 'Moderate',
    lastScan: '2026-08-25T05:39:00Z',
    status: 'Warning',
    location: 'Campus Access',
  },
]

export const findings: Finding[] = [
  {
    id: 'find-001',
    title: 'Telnet enabled on management interface',
    device: 'FW-Perimeter-A',
    vendor: 'Palo Alto',
    framework: 'CIS Benchmarks',
    severity: 'Critical',
    category: 'Management Access',
    status: 'Open',
    detected: '2026-08-25T06:20:00Z',
    action: 'Disable legacy management protocol',
    riskScore: 92,
    controlId: 'CIS-NET-01',
    description: 'The firewall exposes the management interface over Telnet, which transmits credentials in clear text.',
    whyItMatters: 'This exposes remote administrative access to credential theft and session hijacking.',
    evidence: 'telnet enabled',
    currentConfig: 'set deviceconfig system service disable-telnet no',
    recommendedConfig: 'set deviceconfig system service disable-telnet yes',
    remediationCommand: 'set deviceconfig system service disable-telnet yes',
    references: ['CIS 4.1', 'NIST AC-17'],
  },
  {
    id: 'find-002',
    title: 'HTTP management interface enabled',
    device: 'FortiGate-Edge',
    vendor: 'Fortinet',
    framework: 'NIST SP 800-53',
    severity: 'High',
    category: 'Administrative Security',
    status: 'Investigating',
    detected: '2026-08-25T02:10:00Z',
    action: 'Restrict administrative access to HTTPS only',
    riskScore: 82,
    controlId: 'NIST-AC-02',
    description: 'Administrative web access remains available over HTTP, increasing the risk of session disclosure.',
    whyItMatters: 'HTTP exposes command and credential data without transport-layer encryption.',
    evidence: 'HTTP management interface enabled',
    currentConfig: 'config system global\nset admintimeout 10\nend',
    recommendedConfig: 'config system global\nset admin-sport 443\nend',
    remediationCommand: 'config system global\nset admin-sport 443\nend',
    references: ['NIST AC-17', 'ISO 27001 A.8.31'],
  },
  {
    id: 'find-003',
    title: 'Logging destination not configured',
    device: 'MX-Transit',
    vendor: 'Juniper',
    framework: 'DISA STIG',
    severity: 'Medium',
    category: 'Audit Logging',
    status: 'Monitoring',
    detected: '2026-08-24T18:45:00Z',
    action: 'Configure centralized syslog logging',
    riskScore: 65,
    controlId: 'STIG-V-01',
    description: 'The routing platform does not forward security events to an internal log collector.',
    whyItMatters: 'Without centralized logging, incident response and auditability are significantly degraded.',
    evidence: 'logging destination not configured',
    currentConfig: 'set system syslog file messages any any',
    recommendedConfig: 'set system syslog host 10.10.50.20 any any',
    remediationCommand: 'set system syslog host 10.10.50.20 any any',
    references: ['DISA STIG V-1184'],
  },
]

export const analysisJobs: AnalysisJob[] = [
  {
    id: 'job-1001',
    fileName: 'core-edge.cfg',
    device: 'Core-Edge-01',
    vendor: 'Cisco',
    framework: 'CIS Benchmarks',
    progress: 100,
    status: 'Completed',
    started: '2026-08-25T08:00:00Z',
    completed: '2026-08-25T08:06:00Z',
  },
  {
    id: 'job-1002',
    fileName: 'fw-edge.conf',
    device: 'FW-Perimeter-A',
    vendor: 'Palo Alto',
    framework: 'NIST SP 800-53',
    progress: 76,
    status: 'Processing',
    started: '2026-08-25T08:30:00Z',
    completed: null,
  },
  {
    id: 'job-1003',
    fileName: 'fortinet-gateway.log',
    device: 'FortiGate-Edge',
    vendor: 'Fortinet',
    framework: 'ISO/IEC 27001',
    progress: 100,
    status: 'Completed',
    started: '2026-08-25T07:00:00Z',
    completed: '2026-08-25T07:18:00Z',
  },
  {
    id: 'job-1004',
    fileName: 'mx-core.txt',
    device: 'MX-Transit',
    vendor: 'Juniper',
    framework: 'DISA STIG',
    progress: 58,
    status: 'Queued',
    started: '2026-08-25T08:46:00Z',
    completed: null,
  },
]

export const analysisResults: AnalysisResult[] = [
  {
    id: 'result-001',
    jobId: 'job-1001',
    device: 'Core-Edge-01',
    vendor: 'Cisco',
    framework: 'CIS Benchmarks',
    overallScore: 92,
    riskLevel: 'Low',
    controlsChecked: 24,
    passed: 20,
    failed: 2,
    warnings: 2,
    summary: 'Core routing policy is mostly aligned with the benchmark. Remaining gaps are focused on secure remote administration and logging settings.',
    timestamp: '2026-08-25T08:06:00Z',
    controls: [
      { id: 'CIS-NET-01', framework: 'CIS', requirement: 'Disable legacy management protocols', result: 'Fail', severity: 'Critical', evidence: 'telnet enabled', remediation: 'Disable Telnet and enforce SSH v2' },
      { id: 'CIS-NET-02', framework: 'CIS', requirement: 'Use secure remote administration', result: 'Pass', severity: 'High', evidence: 'SSH version 2 configured', remediation: 'Maintain current baseline' },
      { id: 'CIS-NET-03', framework: 'CIS', requirement: 'Restrict administrative access to management VLAN', result: 'Warning', severity: 'Medium', evidence: 'Management plane reachable from non-trusted VLAN', remediation: 'Scope ACL to admin subnet' },
      { id: 'NIST-AC-02', framework: 'NIST', requirement: 'Explicit administrative session controls', result: 'Pass', severity: 'High', evidence: 'Session timeout enabled', remediation: 'Retain current timeout policy' },
      { id: 'NIST-AU-02', framework: 'NIST', requirement: 'Audit logging enabled', result: 'Warning', severity: 'Medium', evidence: 'logging destination not configured', remediation: 'Forward syslog to SIEM collector' },
      { id: 'STIG-V-01', framework: 'STIG', requirement: 'Encryption for management traffic', result: 'Fail', severity: 'High', evidence: 'HTTP management interface enabled', remediation: 'Disable HTTP and enforce HTTPS only' },
      { id: 'ISO-A.8.20', framework: 'ISO', requirement: 'Asset access control review', result: 'Pass', severity: 'Medium', evidence: 'Periodic review in place', remediation: 'Continue quarterly review' },
    ],
  },
  {
    id: 'result-002',
    jobId: 'job-1003',
    device: 'FortiGate-Edge',
    vendor: 'Fortinet',
    framework: 'ISO/IEC 27001',
    overallScore: 71,
    riskLevel: 'Moderate',
    controlsChecked: 18,
    passed: 12,
    failed: 4,
    warnings: 2,
    summary: 'The device is largely compliant, but administrative access and logging controls need alignment with ISO access control requirements.',
    timestamp: '2026-08-25T07:18:00Z',
    controls: [
      { id: 'ISO-A.8.20', framework: 'ISO', requirement: 'Access control management', result: 'Pass', severity: 'Medium', evidence: 'Role-based admin configured', remediation: 'Maintain RBAC' },
      { id: 'ISO-A.8.22', framework: 'ISO', requirement: 'Secure authentication', result: 'Warning', severity: 'Medium', evidence: 'Local admin account still enabled', remediation: 'Disable shared admin accounts' },
      { id: 'ISO-A.8.31', framework: 'ISO', requirement: 'Logging and monitoring', result: 'Fail', severity: 'High', evidence: 'Event logs not forwarded externally', remediation: 'Enable central SIEM export' },
      { id: 'NIST-AC-02', framework: 'NIST', requirement: 'Administrative access restrictions', result: 'Fail', severity: 'High', evidence: 'HTTP management interface enabled', remediation: 'Restrict to HTTPS' },
    ],
  },
]

export const remediationTasks: RemediationTask[] = [
  {
    id: 'rem-001',
    finding: 'Telnet enabled',
    device: 'FW-Perimeter-A',
    severity: 'Critical',
    type: 'Configuration Change',
    command: 'set deviceconfig system service disable-telnet yes',
    status: 'Pending',
  },
  {
    id: 'rem-002',
    finding: 'HTTP management interface enabled',
    device: 'FortiGate-Edge',
    severity: 'High',
    type: 'Access Control',
    command: 'config system global\nset admin-sport 443\nend',
    status: 'In Progress',
  },
  {
    id: 'rem-003',
    finding: 'Logging destination not configured',
    device: 'MX-Transit',
    severity: 'Medium',
    type: 'Monitoring',
    command: 'set system syslog host 10.10.50.20 any any',
    status: 'Pending',
  },
]

export const frameworks: FrameworkDefinition[] = [
  { id: 'fw-cis', name: 'CIS Benchmarks', controls: 128, activeRules: 96, lastUpdated: '2026-08-18', status: 'Healthy' },
  { id: 'fw-nist', name: 'NIST SP 800-53', controls: 254, activeRules: 183, lastUpdated: '2026-08-21', status: 'Monitoring' },
  { id: 'fw-stig', name: 'DISA STIG', controls: 315, activeRules: 221, lastUpdated: '2026-08-17', status: 'Needs Review' },
  { id: 'fw-iso', name: 'ISO/IEC 27001', controls: 159, activeRules: 117, lastUpdated: '2026-08-22', status: 'Healthy' },
]

export const reports: ReportItem[] = [
  { id: 'rpt-001', name: 'Executive Summary - Edge Firewall', device: 'FW-Perimeter-A', vendor: 'Palo Alto', framework: 'CIS Benchmarks', complianceScore: 78, generatedDate: '2026-08-25', status: 'Ready' },
  { id: 'rpt-002', name: 'Branch Security Review', device: 'FortiGate-Edge', vendor: 'Fortinet', framework: 'ISO/IEC 27001', complianceScore: 71, generatedDate: '2026-08-25', status: 'Ready' },
  { id: 'rpt-003', name: 'Transit Core Baseline', device: 'MX-Transit', vendor: 'Juniper', framework: 'DISA STIG', complianceScore: 57, generatedDate: '2026-08-24', status: 'Draft' },
]

export const auditLogs: AuditLog[] = [
  { id: 'log-001', timestamp: '2026-08-25T08:42:00Z', user: 'A. Patel', action: 'Configuration uploaded', resource: 'core-edge.cfg', device: 'Core-Edge-01', result: 'Success', ipAddress: '10.10.10.45' },
  { id: 'log-002', timestamp: '2026-08-25T08:30:00Z', user: 'J. Kim', action: 'Analysis started', resource: 'fw-edge.conf', device: 'FW-Perimeter-A', result: 'Success', ipAddress: '10.10.20.11' },
  { id: 'log-003', timestamp: '2026-08-25T07:20:00Z', user: 'M. Gomez', action: 'Compliance scan completed', resource: 'FortiGate-Edge', device: 'FortiGate-Edge', result: 'Warning', ipAddress: '10.10.30.9' },
  { id: 'log-004', timestamp: '2026-08-25T06:58:00Z', user: 'S. Chen', action: 'Finding resolved', resource: 'Telnet enabled', device: 'FW-Perimeter-A', result: 'Success', ipAddress: '10.10.10.47' },
  { id: 'log-005', timestamp: '2026-08-25T06:04:00Z', user: 'L. Reyes', action: 'AI mapping created', resource: 'legacy-protocol', device: 'Unknown Vendor', result: 'Success', ipAddress: '10.10.40.12' },
  { id: 'log-006', timestamp: '2026-08-25T05:50:00Z', user: 'R. Shah', action: 'Report generated', resource: 'Executive Summary - Edge Firewall', device: 'FW-Perimeter-A', result: 'Success', ipAddress: '10.10.20.5' },
]

export const trainingItems: TrainingItem[] = [
  {
    id: 'train-001',
    command: 'set management access legacy-protocol enable',
    vendor: 'Unknown Vendor',
    mapping: 'legacy_protocol_enabled',
    framework: 'CIS',
    confidence: 91,
    createdBy: 'A. Patel',
    date: '2026-08-25',
    category: 'Management Access',
    parameter: 'insecure_protocol',
    meaning: 'Enables an outdated remote management protocol that bypasses secure administration controls.',
    expectedSecureValue: 'disabled',
  },
  {
    id: 'train-002',
    command: 'admin system no-authentication',
    vendor: 'Custom Appliance',
    mapping: 'admin_auth_disabled',
    framework: 'NIST',
    confidence: 84,
    createdBy: 'J. Kim',
    date: '2026-08-20',
    category: 'Authentication',
    parameter: 'authentication',
    meaning: 'Disables user authentication for administrative access.',
    expectedSecureValue: 'enabled',
  },
]

export const uploadedFiles: UploadRecord[] = [
  { id: 'file-001', filename: 'core-edge.cfg', size: '342 KB', detectedVendor: 'Cisco', deviceType: 'Router', status: 'Detected' },
  { id: 'file-002', filename: 'fw-edge.conf', size: '510 KB', detectedVendor: 'Palo Alto', deviceType: 'Firewall', status: 'Queued' },
  { id: 'file-003', filename: 'mx-core.txt', size: '286 KB', detectedVendor: 'Juniper', deviceType: 'Router', status: 'Analyzing' },
]

export const complianceSnapshot = {
  overallScore: 81,
  totalDevices: 6,
  compliantDevices: 3,
  nonCompliantDevices: 3,
  criticalFindings: 2,
  highRiskFindings: 4,
  configurationsAnalyzed: 184,
  lastAnalysis: '2026-08-25T08:44:00Z',
}

export const complianceTrend = [
  { name: 'Jan', score: 63 },
  { name: 'Feb', score: 68 },
  { name: 'Mar', score: 71 },
  { name: 'Apr', score: 74 },
  { name: 'May', score: 77 },
  { name: 'Jun', score: 79 },
  { name: 'Jul', score: 82 },
  { name: 'Aug', score: 81 },
]

export const severityBreakdown = [
  { name: 'Critical', value: 2 },
  { name: 'High', value: 4 },
  { name: 'Medium', value: 7 },
  { name: 'Low', value: 11 },
]

export const vendorCompliance = [
  { name: 'Cisco', score: 92 },
  { name: 'Palo Alto', score: 78 },
  { name: 'Fortinet', score: 66 },
  { name: 'Juniper', score: 57 },
  { name: 'Arista', score: 88 },
  { name: 'HPE Aruba', score: 83 },
]

export const frameworkComparison = [
  { name: 'CIS', score: 88 },
  { name: 'NIST', score: 81 },
  { name: 'STIG', score: 64 },
  { name: 'ISO', score: 76 },
]
